D:\python\mintos>install.bat
Mintos Telegram Bot Installer
=============================
Python found. Choose installation method:

1. Simple Install (Downloads ZIP, no Git required)
2. Git Install (Requires Git to be installed)
3. Dependencies Only (If you already have the files)

Enter choice (1-3): 2
Installing from Git repository...
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Folky83/RecoveryTBot.git
  Cloning https://github.com/Folky83/RecoveryTBot.git to c:\users\gebruiker\appdata\local\temp\pip-req-build-vso12lki
  Running command git clone --filter=blob:none --quiet https://github.com/Folky83/RecoveryTBot.git 'C:\Users\Gebruiker\AppData\Local\Temp\pip-req-build-vso12lki'
  Resolved https://github.com/Folky83/RecoveryTBot.git to commit 36a3cbdd9abc38a5a1fe09456691a93325d60efd

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 539, in collect_root_requirements
    reqs = list(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 495, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
    super().__init__(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\distributions\sdist.py", line 39, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\req\req_install.py", line 512, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_internal\pyproject.py", line 70, in load_pyproject_toml
    pp_toml = tomllib.loads(f.read())
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\tomli\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
  File "C:\Users\Gebruiker\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\tomli\_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
pip._vendor.tomli.TOMLDecodeError: Cannot overwrite a value (at line 52, column 26)
Git installation failed. Try option 1 instead.
Press any key to continue . . .